### ISSUE TITLE
Gmail test fail

### ISSUE THREAD

**Issue by abnerjacobsen** [embedchain/embedchain#1138]
### 🐛 Describe the bug

When I run this Gmail test code:

```
import os
from embedchain import App

os.environ["OPENAI_API_BASE"] = "https://api.endpoints.anyscale.com/v1"
os.environ['OPENAI_API_KEY'] = 'esecret_xxxxxx...'

app = App()

gmail_filter = "to: me label:inbox newer_than:2d"
app.add(gmail_filter, data_type="gmail")
app.query("Resumir minhas conversas por e-mail")
```
I got this error:

```
Traceback (most recent call last):
  File "/home/abner/Devel/aumo/aumogpt-demos/src/gmail/test1.py", line 10, in <module>
    app.add(gmail_filter, data_type="gmail")
  File "/home/abner/Devel/aumo/aumogpt-demos/.venv/lib/python3.11/site-packages/embedchain/embedchain.py", line 201, in add
    documents, metadatas, _ids, new_chunks = self._load_and_embed(
                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abner/Devel/aumo/aumogpt-demos/.venv/lib/python3.11/site-packages/embedchain/embedchain.py", line 366, in _load_and_embed
    embeddings_data = chunker.create_chunks(loader, src, app_id=app_id, config=add_config.chunker)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abner/Devel/aumo/aumogpt-demos/.venv/lib/python3.11/site-packages/embedchain/chunkers/base_chunker.py", line 46, in create_chunks
    url = meta_data["url"]
          ~~~~~~~~~^^^^^^^
KeyError: 'url'
```
Someone can help me in solve this issue?

I have successfully loged in my Gmail account.

Regards

**Comment by abnerjacobsen** [comment]
Problem solved. As I have the OPENAI module installed in my project with a version > 1, the correct environment variable to be configured is this:

`os.environ["OPENAI_BASE_URL"] = "https://api.endpoints.anyscale.com/v1"`

Somente quen tem o módulo OPERNAI com uma versão <1 é quem deve usar:

`os.environ["OPENAI_API_BASE"] = "https://api.endpoints.anyscale.com/v1"`
