### ISSUE TITLE
I can't initialize the app

### ISSUE THREAD

**Issue by candidosales** [embedchain/embedchain#1164]
### 🐛 Describe the bug

What's happening?

`config.yaml`
```yaml
llm:
  provider: openai
  config:
    model: 'gpt-4-turbo'
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false
vectordb:
  provider: chroma
  config:
    collection_name: 'my-collection'
    dir: db
    allow_reset: true

```

`app.py`
```python
from embedchain import App

chat_bot = App.from_config(config_path="config.yaml")
chat_bot.add("/data/output-2023-06-22T03:37:39.362Z.csv", data_type="csv")
```

```bash
chat-backend on  chromadb-0.4 [!?] via 🐍 3.10.11 via chat-backend 
➜ python test.py          
Traceback (most recent call last):
  File "/Users/candidosales/Documents/Projects/cisco/chat-backend/test.py", line 3, in <module>
    chat_bot = App.from_config(config_path="config.yaml")
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/embedchain/app.py", line 432, in from_config
    db = VectorDBFactory.create(db_provider, db_config_data.get("config", {}))
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/embedchain/factory.py", line 102, in create
    return embedder_class(config=embedder_config_class(**config_data))
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/embedchain/vectordb/chroma.py", line 61, in __init__
    self.client = chromadb.Client(self.settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/__init__.py", line 248, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/api/client.py", line 139, in __init__
    super().__init__(settings=settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/api/client.py", line 43, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/api/client.py", line 54, in _create_system_if_not_exists
    new_system.instance(ServerAPI)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/config.py", line 366, in instance
    impl = type(self)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/api/segment.py", line 103, in __init__
    self._manager = self.require(SegmentManager)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/config.py", line 274, in require
    inst = self._system.instance(type)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/config.py", line 366, in instance
    impl = type(self)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/segment/impl/manager/local.py", line 76, in __init__
    // PersistentLocalHnswSegment.get_file_handle_count()
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/segment/impl/vector/local_persistent_hnsw.py", line 445, in get_file_handle_count
    hnswlib_count = hnswlib.Index.file_handle_count
AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'
```

**Comment by deven298** [comment]
@candidosales Can you please provide the embedchain version you are using?

```
import embedchain
print(embedchain.__version__)
```

**Comment by candidosales** [comment]
@deven298 

-> 0.1.63

```bash
➜ python test.py
0.1.63
Traceback (most recent call last):
  File "/Users/candidosales/Documents/Projects/cisco/chat-backend/test.py", line 7, in <module>
    chat_bot = App.from_config(config_path="config.yaml")
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/embedchain/app.py", line 432, in from_config
    db = VectorDBFactory.create(db_provider, db_config_data.get("config", {}))
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/embedchain/factory.py", line 102, in create
    return embedder_class(config=embedder_config_class(**config_data))
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/embedchain/vectordb/chroma.py", line 61, in __init__
    self.client = chromadb.Client(self.settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/__init__.py", line 248, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/api/client.py", line 139, in __init__
    super().__init__(settings=settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/api/client.py", line 43, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/api/client.py", line 54, in _create_system_if_not_exists
    new_system.instance(ServerAPI)
  File "/Users/candidosales/.pyenv/versions/chat-backend/lib/python3.10/site-packages/chromadb/config.py", line 366, in instance
    impl = type(self)
```

**Comment by candidosales** [comment]
I found the issue. It was something related with which python version the poetry was using.
