### ISSUE TITLE
What is this error in the ollama example?

### ISSUE THREAD

**Issue by shersoni610** [embedchain/embedchain#1210]
### 🐛 Describe the bug

Hello, 

While using Ollama example posted in the document. I get the following message:

Inserting batches in chromadb:   0%|                                      | 0/1 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/ollamachat.py", line 24, in <module>
    app.add(url)
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/embedchain/embedchain.py", line 201, in add
    documents, metadatas, _ids, new_chunks = self._load_and_embed(
                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/embedchain/embedchain.py", line 436, in _load_and_embed
    self.db.add(documents=documents, metadatas=metadatas, ids=ids, **kwargs)
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/embedchain/vectordb/chroma.py", line 154, in add
    self.collection.add(
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 168, in add
    self._client._add(ids, self.id, embeddings, metadatas, documents, uris)
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/chromadb/api/segment.py", line 375, in _add
    self._validate_embedding_record(coll, r)
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/chromadb/api/segment.py", line 799, in _validate_embedding_record
    self._validate_dimension(collection, len(record["embedding"]), update=True)
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/NLP/EmbedChain/embedenv/lib/python3.11/site-packages/chromadb/api/segment.py", line 814, in _validate_dimension
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536/

What could be the error?

Thanks

**Comment by deven298** [comment]
Hey! Please delete the local existing db folder with (rm -rf db) command and try to add the document again. You might have used the hugging face model earlier to add some data which had (384) dimensions and now using openai embedding model which has higher dimensions, hence the error.

**Comment by shersoni610** [comment]
Thanks for the prompt reply. It worked
