### ISSUE TITLE
Mistral llm not working 

### ISSUE THREAD

**Issue by chiragksharma** [embedchain/embedchain#1241]
### 🐛 Describe the bug

I am creating an app which is to be deployed on Railway app. While deploying it shows the error again and again 

Traceback (most recent call last):

```
File "/app/app.py", line 13, in <module>

embedchain_app = Pipeline()

^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/embedchain/app.py", line 118, in __init__

self.embedding_model = embedding_model or OpenAIEmbedder()

^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/embedchain/embedder/openai.py", line 19, in __init__

api_key = self.config.api_key or os.environ["OPENAI_API_KEY"]

~~~~~~~~~~^^^^^^^^^^^^^^^^^^

File "<frozen os>", line 679, in __getitem__

KeyError: 'OPENAI_API_KEY'
```

In environment variables I have already entered the Mistral api key 
and changed the app configurations in my app still it is showing the same error. 

**app.py code** 
```py
app_config = {
    "app": {
        "config": {
            "id": "embedchain-demo-app"
        }
    },
    "llm": {
        "provider": "huggingface",
        "config": {
            "model": "mistralai/Mixtral-8x7B-Instruct-v0.1",
            "temperature": 0.1,
            "max_tokens": 250,
            "top_p": 0.1
        }
    },
    "embedder": {
        "provider": "huggingface",
        "config": {
            "model": "sentence-transformers/all-mpnet-base-v2"
        }
    }
}

ec_app = Pipeline.from_config(config=app_config)
```

**Comment by deshraj** [comment]
Thanks for reporting the issue. @chiragksharma I am looking into this issue now.
