### ISSUE TITLE
DOC: Following Quick Start with Hugging Face and error (Python 3.12.2, embedchain 0.1.84)

### ISSUE THREAD

**Issue by PhilFlash** [embedchain/embedchain#1283]
### 🐛 Describe the bug

Try documentation for Hugging Face and Mistral (with Windows 10, Python 3.12.2, embedchain 0.1.84
and an User Access Tokens for Huggin Face in READ mode)

First call with: python quickstart.py

```
Traceback (most recent call last):
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table ec_chat_history already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\pythonProjects\embedchain_ex1\quickstart.py", line 9, in <module>
    app = App.from_config("mistral.yaml")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\embedchain\app.py", line 387, in from_config
    init_db()
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\embedchain\core\db\database.py", line 75, in init_db
    alembic_upgrade()
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\embedchain\core\db\database.py", line 71, in alembic_upgrade
    command.upgrade(alembic_cfg, "head")
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\command.py", line 403, in upgrade
    script.run_env()
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\script\base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\embedchain\migrations\env.py", line 74, in <module>
    run_migrations_online()
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\embedchain\migrations\env.py", line 68, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\runtime\environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\runtime\migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\embedchain\migrations\versions\40a327b3debd_create_initial_migrations.py", line 23, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\operations\ops.py", line 1311, in create_table
    return operations.invoke(op)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\operations\base.py", line 445, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\operations\toimpl.py", line 131, in create_table
    operations.impl.create_table(table)
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\ddl\impl.py", line 366, in create_table
    self._exec(schema.CreateTable(table))
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\alembic\ddl\impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1519, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1839, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "E:\pythonProjects\embedchain_ex1\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table ec_chat_history already exists
[SQL:
CREATE TABLE ec_chat_history (
        app_id VARCHAR NOT NULL,
        id VARCHAR NOT NULL,
        session_id VARCHAR NOT NULL,
        question TEXT,
        answer TEXT,
        metadata TEXT,
        created_at TIMESTAMP,
        PRIMARY KEY (app_id, id, session_id)
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

All is ok with Python 3.11.8 and embedchain 0.1.81

**Comment by deshraj** [comment]
Hey, can you please do the following and try again `rm -rf ~/.embedchain` ? This should resolve the issue.

**Comment by PhilFlash** [comment]
On Windows, use %USERPROFILE% in Explorer and delete .embedchain
Thanks
All is ok
