### ISSUE TITLE
sqlite3.OperationalError: table ec_chat_history already exists

### ISSUE THREAD

**Issue by FrankTseng168** [embedchain/embedchain#1354]
### 🐛 Describe the bug

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\embedchain\Lib\site-packages\sqlalchemy\engine\base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "C:\ProgramData\anaconda3\envs\embedchain\Lib\site-packages\sqlalchemy\engine\default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table ec_chat_history already exists

**Comment by FrankTseng168** [comment]
serach .embedchain in file manager then delete it.

**Comment by wgong** [comment]
@FrankTseng168 Which root folder should I start the search for `.embedchain` file? I got the same error after installing embedchain in a conda env for the first time, Thanks
