### ISSUE TITLE
HF_HUB_CACHE not present (see error message)

### ISSUE THREAD

**Issue by jonabert** [embedchain/embedchain#1418]
### 🐛 Describe the bug

Done in 0.13s.
✅ UI server started successfully.
yarn run v1.22.22
$ next dev
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env.local

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jonathan/programming/langer/kk/embedchain/my-app/api/main.py", line 6, in <module>
    from routes.admin import chat_history, data_sources, vector_stores
  File "/home/jonathan/programming/langer/kk/embedchain/my-app/api/routes/admin/chat_history.py", line 5, in <module>
    ec_app = App.from_config(config_path="/home/jonathan/config.yaml")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/embedchain/app.py", line 388, in from_config
    embedding_model = EmbedderFactory.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/embedchain/factory.py", line 81, in create
    return embedder_class(config=embedder_config_class(**config_data))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/embedchain/embedder/huggingface.py", line 14, in __init__
    embeddings = HuggingFaceEmbeddings(model_name=self.config.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 64, in __init__
    import sentence_transformers
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/sentence_transformers/__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/sentence_transformers/cross_encoder/__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 12, in <module>
    from transformers import AutoConfig, AutoModelForSequenceClassification, AutoTokenizer, is_torch_npu_available
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/transformers/utils/__init__.py", line 63, in <module>
    from .hub import (
  File "/home/jonathan/anaconda3/envs/embedch/lib/python3.12/site-packages/transformers/utils/hub.py", line 96, in <module>
    PYTORCH_PRETRAINED_BERT_CACHE = os.getenv("PYTORCH_PRETRAINED_BERT_CACHE", constants.HF_HUB_CACHE)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'huggingface_hub.constants' has no attribute 'HF_HUB_CACHE'
 ✓ Ready in 2.2s

**Comment by jonabert** [comment]
works
