### ISSUE TITLE
ImportError: cannot import name 'App' from 'embedchain'

### ISSUE THREAD

**Issue by love2210** [embedchain/embedchain#427]
HI~
I use Python 3.11.3 run my test code, but I got this errer message.
`from embedchain import App`
`naval_chat_bot.add("web_page", "https://XXXXXX")`

Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap      
    self.run()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete  
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\config.py", line 467, in load       
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module        
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SourceCode\TEST\linebot-embedchain-master\main.py", line 26, in <module>
    from embedchain import App
ImportError: cannot import name 'App' from 'embedchain' (C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\embedchain\__init__.py)

**Comment by taranjeet** [comment]
Hey, can you please share more details?

i tried the following code snippet and its working fine for me.

```
from embedchain import App

naval_chat_bot = App()
naval_chat_bot.add("web_page", "https://nav.al")

```

**Comment by taranjeet** [comment]
hi @love2210 : let us know if you are still facing the issue?
Feel free to close if this issue is resolved.

**Comment by cachho** [comment]
Closing this, as we have no reproducible code.
