### ISSUE TITLE
Can not process realistic documentation sties like docker API

### ISSUE THREAD

**Issue by erikatlassian** [embedchain/embedchain#619]
### 🐛 Describe the bug

with the code below, I am trying to get some knowledge from the docker API documentation site `https://docs.docker.com/engine/api/`  and it has the error, and same if I added the documentation of embedchain itself `https://docs.embedchain.ai` and it would says that the maximum recursion stack depth reached
```python
from embedchain import App

web_bot = App()

# Embed Online Resources
web_bot.add("https://docs.docker.com/engine/api/")
response = web_bot.query("how to use docker api to create a container")
print(response)
```

```shell
Traceback (most recent call last):
  File "/Users/ezhou2/Desktop/erik-llm-playground/src/main.py", line 12, in <module>
    web_bot.add("https://docs.docker.com/engine/api/")
  File "/Users/ezhou2/Desktop/erik-llm-playground/venv/lib/python3.9/site-packages/embedchain/embedchain.py", line 184, in add
    documents, metadatas, _ids, new_chunks = self.load_and_embed_v2(
  File "/Users/ezhou2/Desktop/erik-llm-playground/venv/lib/python3.9/site-packages/embedchain/embedchain.py", line 455, in load_and_embed_v2
    self.db.add(documents=documents, metadatas=metadatas, ids=ids)
  File "/Users/ezhou2/Desktop/erik-llm-playground/venv/lib/python3.9/site-packages/embedchain/vectordb/chroma.py", line 126, in add
    self.collection.add(documents=documents, metadatas=metadatas, ids=ids)
  File "/Users/ezhou2/Desktop/erik-llm-playground/venv/lib/python3.9/site-packages/chromadb/api/models/Collection.py", line 99, in add
    self._client._add(ids, self.id, embeddings, metadatas, documents)
  File "/Users/ezhou2/Desktop/erik-llm-playground/venv/lib/python3.9/site-packages/chromadb/api/segment.py", line 247, in _add
    self._validate_embedding_record(coll, r)
  File "/Users/ezhou2/Desktop/erik-llm-playground/venv/lib/python3.9/site-packages/chromadb/api/segment.py", line 537, in _validate_embedding_record
    self._validate_dimension(collection, len(record["embedding"]), update=True)
  File "/Users/ezhou2/Desktop/erik-llm-playground/venv/lib/python3.9/site-packages/chromadb/api/segment.py", line 552, in _validate_dimension
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Embedding dimension 1 does not match collection dimensionality 1536

```

**Comment by deshraj** [comment]
Seems like automatically resolving the data_type is not working well here. I was able to make it work using the `data_type='web_page'` in this case.


See updated code below:

```python
from embedchain import App
web_bot = App()
web_bot.add("https://docs.docker.com/engine/api/", data_type="web_page")
response = web_bot.query("how to use docker api to create a container")
print(response)

To use the Docker API to create a container, you can make a POST request to the `/containers/create` endpoint. This endpoint allows you to specify the configuration of the container, such as the image to use, the command to run, and any necessary environment variables or volumes.

You can use the Docker CLI or the Docker Engine SDKs to make this API request. If you want to use an older version of the API, you can set the `DOCKER_API_VERSION` environment variable to the desired version before making the request. For example, you can set `DOCKER_API_VERSION='1.41'` to use version 1.41 of the API.

Please note that the specific details of the API request will depend on the programming language or tool you are using to interact with the Docker API.

```

**Comment by deshraj** [comment]
@cachho I think we should just fix this natively in the package, right?

**Comment by cachho** [comment]
@deshraj we must have the `docs_site` loader for a reason. That was used instead of the web page. I think the type detection is working as intended.

The question is why the docs site isn't working.

**Comment by cachho** [comment]
This error `chromadb.errors.InvalidDimensionException: Embedding dimension 1 does not match collection dimensionality 1536` sounds like you might have to reset your database. Can you try that? Just delete the `db` folder. If it still appears we have to investigate. But usually these kind of errors come when embedding and query were done with different dimensions.

**Comment by cachho** [comment]
Opened #622 to track the issue with `docs_site`.

Your issue is a different one @erikatlassian - it has to do with vector dimensions. Did you manage to resolve it by resetting the db? Then I will close this.

**Comment by parshvadaftari** [comment]
Closing as duplicate
