### ISSUE TITLE
Azure OpenAI support for Embeddings still not working. v0.1.19

### ISSUE THREAD

**Issue by ghoshaishik505** [embedchain/embedchain#972]
### 🐛 Describe the bug

Hi @deshraj 
Post updating to v0.1.19 after the issue #925 was closed, the issue with Azure OpenAI is still not over. For embedding, Embedchain is using the Langchain/embeddings/openai.py instead of Langchain/embeddings/azure_openai.py
Post that a warning comes up followed with errors.

"""
/MiDir/MyBot/env/lib/python3.9/site-packages/langchain/embeddings/openai.py:319: UserWarning: If you have openai>=1.0.0 installed and are using Azure, please use the `AzureOpenAIEmbeddings` class.
  warnings.warn(
Adding Data
Inserting batches in chromadb:   0%|                                                                                                                                                  | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/MiDir/MyBot/sample.py", line 7, in <module>
    app.add(source = "./datasources/document.pdf", data_type="pdf_file")
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/embedchain/embedchain.py", line 206, in add
    documents, metadatas, _ids, new_chunks = self._load_and_embed(
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/embedchain/embedchain.py", line 438, in _load_and_embed
    self.db.add(
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/embedchain/vectordb/chroma.py", line 170, in add
    self.collection.add(
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/chromadb/api/models/Collection.py", line 147, in add
    embeddings = self._embed(input=documents)
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/chromadb/api/models/Collection.py", line 587, in _embed
    return self._embedding_function(input=input)
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/embedchain/embedder/base.py", line 19, in __call__
    return self.embedding_fn(input)
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 555, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 431, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 106, in embed_with_retry
    return embeddings.client.create(**kwargs)
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/openai/resources/embeddings.py", line 105, in create
    return self._post(
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/openai/_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
  File "/MiDir/MyBot/env/lib/python3.9/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
"""

Same code, and same keys tested with embedchain version 0.0.74 works fine

**Comment by deshraj** [comment]
Sorry for the inconvenience @ghoshaishik505.

I just published an alpha version of the package for you to test. Can you please try installing `pip install embedchain==0.1.20a1` and see if it solves the problem for you? If yes, I will create a PR and merge my changes. Thanks!

**Comment by ghoshaishik505** [comment]
Yes @deshraj this version works. Thanks for the prompt update!
Just to add, now the env variables must be set as:
"""
OPENAI_API_TYPE = azure
AZURE_OPENAI_ENDPOINT= xxx
OPENAI_API_VERSION= xxx
AZURE_OPENAI_API_KEY =xxx
"""
Hope this helps!
Regards @ghoshaishik505

**Comment by deshraj** [comment]
Yes, updated the docs as well. Please check https://docs.embedchain.ai/components/embedding-models#azure-openai
